import Head from "next/head";
import { App } from "@/components/app";

export default function Home() {
  return (
    <>
      <Head>
        <title>ConceptCove</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App />
    </>
  );
}
